encoder: 
  channel_depth: 64
  channel_mults: [1, 2, 3, 4, 4]
  act: "silu"
  norm: "rms"
  winit: "normal"
  debug_outer: True
  kernel_size: 5
  stride: 2
  minres: 4
  cdtype: "bfloat16"
rssm: 
  deter: 8192
  hidden: 1024
  action_dim: 5
  latent_dim: 32
  latent_cls: 64
  channel_depth: 64
  channel_mults: [1, 2, 3, 4, 4]
  act: "silu"
  norm: "rms"
  unimix: 0.01
  outscale: 1.0
  winit: "normal"
  num_imglayer: 2
  num_obslayer: 1
  num_dynlayer: 1
  blocks: 8
  block_fans: False
  block_norm: False
  cdtype: "bfloat16"
            
decoder: 
  deter: 8192
  channel_depth: 64
  channel_mults: [1, 2, 3, 4, 4]
  latent_dim: 32
  latent_cls: 64
  num_units: 1024
  act: "silu"
  norm: "rms"
  winit: "normal"
  debug_outer: True
  kernel_size: 5
  stride: 2
  minres: 4
  use_sigmoid: True
  cdtype: "bfloat16"
            
reward_head: 
  num_layers: 1
  in_features: 10240
  num_units: 1024
  act: "silu"
  norm: "rms"
  dist: "symexp_twohot"
  outscale: 0.0
  winit: "normal"
  cdtype: "bfloat16"
          
cont_head: 
  num_layers: 1
  in_features: 10240
  num_units: 1024
  act: "silu"
  norm: "rms"
  dist: "binary"
  outscale: 1.0
  winit: "normal"
  cdtype: "bfloat16"
            
seed: 0
gpu_id: 0
lr: 4e-5
batch_size: 16
traj_length: 64
precision: 32
num_epoch: 10000


hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_rssm_detersize_${rssm.deter}